--- #YAML:1.0
name: Class-Meta-Declare
version: 0.03
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: "Simple Class::Meta interface"
license: perl
generated_by: Module::Build version 0.2704, without YAML.pm
