--- #YAML:1.0
name: Class-Meta-Declare
version: 0.04
author:
  - 'Curtis "Ovid" Poe <ovid@cpan.org>'
abstract: "Deprecated in favor of Class::Meta::Express"
license: perl
generated_by: Module::Build version 0.2704, without YAML.pm
