---
name: Class-Meta-Declare
version: 0.02
author:
  - Curtis "Ovid" Poe <ovid@cpan.org>
abstract: Simple Class::Meta interface
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Class::BuildMethods: 0.1
  Class::Meta: 0.49
  Exporter::Tidy: 0.06
  Readonly: 1.03
  Test::More: 0
provides:
  Class::Meta::Declare:
    file: lib/Class/Meta/Declare.pm
    version: 0.02
generated_by: Module::Build version 0.2703
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
